//HintName: PingMessage.Outbox.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Outbox;

internal sealed class PingMessageOutboxWriter : global::ZeroAlloc.Outbox.IOutboxWriter<global::PingMessage>
{
    private readonly global::ZeroAlloc.Outbox.IOutboxStore _store;
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;

    public PingMessageOutboxWriter(
        global::ZeroAlloc.Outbox.IOutboxStore store,
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer)
    {
        _store = store;
        _serializer = serializer;
    }

    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "IOutboxSerializer is provided by the consumer; its trim-unsafety is their concern. The generated writer/dispatcher only forwards the call.")]
    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("AOT", "IL3050", Justification = "IOutboxSerializer is provided by the consumer; its AOT-unsafety is their concern. The generated writer/dispatcher only forwards the call.")]
    public global::System.Threading.Tasks.ValueTask WriteAsync(
        global::PingMessage message,
        global::System.Data.Common.DbTransaction? transaction,
        global::System.Threading.CancellationToken ct)
        => _store.EnqueueAsync("PingMessage", _serializer.Serialize(message), transaction, ct);
}

internal sealed class PingMessageOutboxTypeDispatcher : global::ZeroAlloc.Outbox.IOutboxTypeDispatcher
{
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;
    private readonly global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage> _dispatcher;

    public PingMessageOutboxTypeDispatcher(
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer,
        global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage> dispatcher)
    {
        _serializer = serializer;
        _dispatcher = dispatcher;
    }

    public string TypeName => "PingMessage";

    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "IOutboxSerializer is provided by the consumer; its trim-unsafety is their concern. The generated writer/dispatcher only forwards the call.")]
    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("AOT", "IL3050", Justification = "IOutboxSerializer is provided by the consumer; its AOT-unsafety is their concern. The generated writer/dispatcher only forwards the call.")]
    public global::System.Threading.Tasks.ValueTask DispatchAsync(
        global::System.ReadOnlyMemory<byte> payload,
        global::System.Threading.CancellationToken ct)
    {
        var message = _serializer.Deserialize<global::PingMessage>(payload);
        return _dispatcher.DispatchAsync(message, ct);
    }
}

public static partial class OutboxServiceCollectionExtensions
{
    public static global::ZeroAlloc.Outbox.IOutboxBuilder AddPingMessageOutbox(
        this global::ZeroAlloc.Outbox.IOutboxBuilder builder)
    {
        builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::PingMessage>, PingMessageOutboxWriter>();
        builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, PingMessageOutboxTypeDispatcher>();
        builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage>,
            global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::PingMessage>>();
        return builder;
    }

    [global::System.Obsolete("Use AddOutbox().AddPingMessageOutbox() instead. Will be removed in the next major.", DiagnosticId = "ZAOBOX010")]
    [global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("AddOutbox may register SystemTextJsonOutboxSerializer which uses reflection-based JSON. Call services.AddSerializerDispatcher() first for AOT-safe serialisation.")]
    [global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode("AddOutbox may register SystemTextJsonOutboxSerializer which may require runtime code generation. Call services.AddSerializerDispatcher() first for AOT-safe serialisation.")]
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPingMessageOutbox(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddOutbox().AddPingMessageOutbox();
        return services;
    }
}
