//HintName: PingMessage.Outbox.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable IL2026, IL3050 // IOutboxSerializer methods carry RequiresUnreferencedCode/RequiresDynamicCode; suppress in generated callers

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

internal sealed class PingMessageOutboxWriter : global::ZeroAlloc.Outbox.IOutboxWriter<global::PingMessage>
{
    private readonly global::ZeroAlloc.Outbox.IOutboxStore _store;
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;

    public PingMessageOutboxWriter(
        global::ZeroAlloc.Outbox.IOutboxStore store,
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer)
    {
        _store = store;
        _serializer = serializer;
    }

    public global::System.Threading.Tasks.ValueTask WriteAsync(
        global::PingMessage message,
        global::System.Data.Common.DbTransaction? transaction,
        global::System.Threading.CancellationToken ct)
        => _store.EnqueueAsync("PingMessage", _serializer.Serialize(message), transaction, ct);
}

internal sealed class PingMessageOutboxTypeDispatcher : global::ZeroAlloc.Outbox.IOutboxTypeDispatcher
{
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;
    private readonly global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage> _dispatcher;

    public PingMessageOutboxTypeDispatcher(
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer,
        global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage> dispatcher)
    {
        _serializer = serializer;
        _dispatcher = dispatcher;
    }

    public string TypeName => "PingMessage";

    public global::System.Threading.Tasks.ValueTask DispatchAsync(
        global::System.ReadOnlyMemory<byte> payload,
        global::System.Threading.CancellationToken ct)
    {
        var message = _serializer.Deserialize<global::PingMessage>(payload);
        return _dispatcher.DispatchAsync(message, ct);
    }
}

public static partial class OutboxServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPingMessageOutbox(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::PingMessage>, PingMessageOutboxWriter>();
        services.AddSingleton<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, PingMessageOutboxTypeDispatcher>();
        services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage>,
            global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::PingMessage>>();
        return services;
    }
}
