using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace ZeroAlloc.Outbox.Generator;

internal static class OutboxCodeWriter
{
    private static string WriterClassName(string typeName) => $"{typeName}OutboxWriter";
    private static string DispatcherClassName(string typeName) => $"{typeName}OutboxTypeDispatcher";
    private static string DiExtensionMethodName(string typeName) => $"Add{typeName}Outbox";

    public static void Write(SourceProductionContext ctx, OutboxModel model)
    {
        var sb = new StringBuilder();
        var typeFqn = $"global::{model.TypeFqn}";
        var writerName = WriterClassName(model.TypeName);
        var dispatcherName = DispatcherClassName(model.TypeName);
        var diMethodName = DiExtensionMethodName(model.TypeName);

        AppendFileHeader(sb, model.Namespace);
        AppendWriter(sb, typeFqn, writerName, model.TypeFqn);
        AppendDispatcher(sb, typeFqn, dispatcherName, model.TypeFqn);
        AppendDiExtension(sb, typeFqn, writerName, dispatcherName, diMethodName);

        var hint = model.Namespace != null
            ? $"{model.Namespace}_{model.TypeName}.Outbox.g.cs"
            : $"{model.TypeName}.Outbox.g.cs";

        ctx.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void AppendFileHeader(StringBuilder sb, string? ns)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable IL2026, IL3050");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
    }

    private static void AppendWriter(StringBuilder sb, string typeFqn, string writerName, string typeKey)
    {
        sb.AppendLine($"internal sealed class {writerName} : global::ZeroAlloc.Outbox.IOutboxWriter<{typeFqn}>");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::ZeroAlloc.Outbox.IOutboxStore _store;");
        sb.AppendLine("    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;");
        sb.AppendLine();
        sb.AppendLine($"    public {writerName}(");
        sb.AppendLine("        global::ZeroAlloc.Outbox.IOutboxStore store,");
        sb.AppendLine("        global::ZeroAlloc.Outbox.IOutboxSerializer serializer)");
        sb.AppendLine("    {");
        sb.AppendLine("        _store = store;");
        sb.AppendLine("        _serializer = serializer;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public global::System.Threading.Tasks.ValueTask WriteAsync(");
        sb.AppendLine($"        {typeFqn} message,");
        sb.AppendLine("        global::System.Data.Common.DbTransaction? transaction,");
        sb.AppendLine("        global::System.Threading.CancellationToken ct)");
        sb.AppendLine($"        => _store.EnqueueAsync(\"{typeKey}\", _serializer.Serialize(message), transaction, ct);");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendDispatcher(StringBuilder sb, string typeFqn, string dispatcherName, string typeKey)
    {
        sb.AppendLine($"internal sealed class {dispatcherName} : global::ZeroAlloc.Outbox.IOutboxTypeDispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;");
        sb.AppendLine($"    private readonly global::ZeroAlloc.Outbox.IOutboxDispatcher<{typeFqn}> _dispatcher;");
        sb.AppendLine();
        sb.AppendLine($"    public {dispatcherName}(");
        sb.AppendLine("        global::ZeroAlloc.Outbox.IOutboxSerializer serializer,");
        sb.AppendLine($"        global::ZeroAlloc.Outbox.IOutboxDispatcher<{typeFqn}> dispatcher)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serializer = serializer;");
        sb.AppendLine("        _dispatcher = dispatcher;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public string TypeName => \"{typeKey}\";");
        sb.AppendLine();
        sb.AppendLine("    public global::System.Threading.Tasks.ValueTask DispatchAsync(");
        sb.AppendLine("        global::System.ReadOnlyMemory<byte> payload,");
        sb.AppendLine("        global::System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var message = _serializer.Deserialize<{typeFqn}>(payload);");
        sb.AppendLine("        return _dispatcher.DispatchAsync(message, ct);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendDiExtension(
        StringBuilder sb,
        string typeFqn,
        string writerName,
        string dispatcherName,
        string diMethodName)
    {
        sb.AppendLine("public static partial class OutboxServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {diMethodName}(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddTransient<global::ZeroAlloc.Outbox.IOutboxWriter<{typeFqn}>, {writerName}>();");
        sb.AppendLine($"        services.AddSingleton<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, {dispatcherName}>();");
        sb.AppendLine($"        services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<{typeFqn}>,");
        sb.AppendLine($"            global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<{typeFqn}>>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
