using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace ZeroAlloc.Outbox.Generator;

internal static class OutboxCodeWriter
{
    private static string WriterClassName(string typeName) => $"{typeName}OutboxWriter";
    private static string DispatcherClassName(string typeName) => $"{typeName}OutboxTypeDispatcher";
    private static string DiExtensionMethodName(string typeName) => $"Add{typeName}Outbox";

    public static void Write(SourceProductionContext ctx, OutboxModel model)
    {
        var sb = new StringBuilder();
        var typeFqn = $"global::{model.TypeFqn}";
        var writerName = WriterClassName(model.TypeName);
        var dispatcherName = DispatcherClassName(model.TypeName);
        var diMethodName = DiExtensionMethodName(model.TypeName);

        AppendFileHeader(sb, model.Namespace);
        AppendWriter(sb, typeFqn, writerName, model.TypeFqn);
        AppendDispatcher(sb, typeFqn, dispatcherName, model.TypeFqn);
        AppendDiExtension(sb, typeFqn, writerName, dispatcherName, diMethodName);

        ctx.AddSource(model.HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Writes the file of a generic message type: a writer and a type dispatcher for each closed
    /// construction, named after its <see cref="ClosedMessage.Identifier"/>, and one
    /// <c>Add{Name}Outbox</c> that registers them all. Each names its closed type and stored name
    /// directly, so nothing is resolved by reflection at run time.
    /// </summary>
    public static void WriteClosedGenerics(
        SourceProductionContext ctx,
        OutboxModel definition,
        System.Collections.Generic.IReadOnlyList<ClosedMessage> messages)
    {
        var sb = new StringBuilder();
        AppendFileHeader(sb, definition.Namespace);

        foreach (var message in messages)
        {
            AppendWriter(sb, message.Reference, WriterClassName(message.Identifier), message.StoredName);
            AppendDispatcher(sb, message.Reference, DispatcherClassName(message.Identifier), message.StoredName);
        }

        sb.AppendLine("public static partial class OutboxServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Registers the outbox writer and type dispatcher of every closed construction of {EscapeXml(definition.DisplayName)}");
        sb.AppendLine("    /// the generator found in this assembly.");
        sb.AppendLine("    /// </summary>");
        AppendNamedPipelineRemarks(sb);
        sb.AppendLine($"    public static global::ZeroAlloc.Outbox.IOutboxBuilder {DiExtensionMethodName(definition.TypeName)}(");
        sb.AppendLine("        this global::ZeroAlloc.Outbox.IOutboxBuilder builder)");
        sb.AppendLine("    {");
        var registrations = new System.Collections.Generic.List<(string, string, string)>(messages.Count);
        foreach (var message in messages)
        {
            registrations.Add((message.Reference, WriterClassName(message.Identifier), DispatcherClassName(message.Identifier)));
        }
        AppendRegistrations(sb, registrations);
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource(definition.HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string EscapeXml(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static void AppendFileHeader(StringBuilder sb, string? ns)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using ZeroAlloc.Outbox;");
        sb.AppendLine();

        if (ns != null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
    }

    private static void AppendWriter(StringBuilder sb, string typeFqn, string writerName, string typeKey)
    {
        sb.AppendLine($"internal sealed class {writerName} : global::ZeroAlloc.Outbox.IOutboxWriter<{typeFqn}>");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::ZeroAlloc.Outbox.IOutboxStore _store;");
        sb.AppendLine("    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;");
        sb.AppendLine();
        sb.AppendLine($"    public {writerName}(");
        sb.AppendLine("        global::ZeroAlloc.Outbox.IOutboxStore store,");
        sb.AppendLine("        global::ZeroAlloc.Outbox.IOutboxSerializer serializer)");
        sb.AppendLine("    {");
        sb.AppendLine("        _store = store;");
        sb.AppendLine("        _serializer = serializer;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public global::System.Threading.Tasks.ValueTask WriteAsync(");
        sb.AppendLine($"        {typeFqn} message,");
        sb.AppendLine("        global::System.Data.Common.DbTransaction? transaction,");
        sb.AppendLine("        global::System.Threading.CancellationToken ct)");
        sb.AppendLine($"        => _store.EnqueueAsync(\"{typeKey}\", _serializer.Serialize(message), transaction, ct);");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendDispatcher(StringBuilder sb, string typeFqn, string dispatcherName, string typeKey)
    {
        sb.AppendLine($"internal sealed class {dispatcherName} : global::ZeroAlloc.Outbox.IOutboxTypeDispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;");
        sb.AppendLine($"    private readonly global::ZeroAlloc.Outbox.IOutboxDispatcher<{typeFqn}> _dispatcher;");
        sb.AppendLine();
        sb.AppendLine($"    public {dispatcherName}(");
        sb.AppendLine("        global::ZeroAlloc.Outbox.IOutboxSerializer serializer,");
        sb.AppendLine($"        global::ZeroAlloc.Outbox.IOutboxDispatcher<{typeFqn}> dispatcher)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serializer = serializer;");
        sb.AppendLine("        _dispatcher = dispatcher;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public string TypeName => \"{typeKey}\";");
        sb.AppendLine();
        sb.AppendLine("    public global::System.Threading.Tasks.ValueTask DispatchAsync(");
        sb.AppendLine("        global::System.ReadOnlyMemory<byte> payload,");
        sb.AppendLine("        global::System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var message = _serializer.Deserialize<{typeFqn}>(payload);");
        sb.AppendLine("        return _dispatcher.DispatchAsync(message, ct);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendDiExtension(
        StringBuilder sb,
        string typeFqn,
        string writerName,
        string dispatcherName,
        string diMethodName)
    {
        sb.AppendLine("public static partial class OutboxServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers the outbox writer and type dispatcher of this message type.");
        sb.AppendLine("    /// </summary>");
        AppendNamedPipelineRemarks(sb);
        sb.AppendLine($"    public static global::ZeroAlloc.Outbox.IOutboxBuilder {diMethodName}(");
        sb.AppendLine("        this global::ZeroAlloc.Outbox.IOutboxBuilder builder)");
        sb.AppendLine("    {");
        AppendRegistrations(sb, [(typeFqn, writerName, dispatcherName)]);
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void AppendNamedPipelineRemarks(StringBuilder sb)
    {
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine("    /// On a named pipeline's builder the writer is registered keyed by the pipeline's name, and");
        sb.AppendLine("    /// writes to that pipeline's store: inject it with <c>[FromKeyedServices(name)]</c>. The type");
        sb.AppendLine("    /// dispatcher is shared by every pipeline.");
        sb.AppendLine("    /// </remarks>");
    }

    /// <summary>
    /// Writes the body of an <c>Add{Name}Outbox</c> method. On the default pipeline's builder it
    /// registers exactly what it always did. On a named pipeline's builder it registers each writer
    /// keyed by the pipeline's name, built on that pipeline's keyed store, and each type dispatcher
    /// only when that dispatcher is not registered yet, since dispatchers are shared.
    /// </summary>
    private static void AppendRegistrations(
        StringBuilder sb,
        System.Collections.Generic.IReadOnlyList<(string TypeFqn, string WriterName, string DispatcherName)> registrations)
    {
        sb.AppendLine("        if (builder is global::ZeroAlloc.Outbox.INamedOutboxBuilder named)");
        sb.AppendLine("        {");
        foreach (var (typeFqn, writerName, dispatcherName) in registrations)
        {
            sb.AppendLine($"            builder.Services.TryAddKeyedTransient<global::ZeroAlloc.Outbox.IOutboxWriter<{typeFqn}>>(");
            sb.AppendLine("                named.Name,");
            sb.AppendLine($"                static (sp, key) => new {writerName}(");
            sb.AppendLine("                    sp.GetRequiredKeyedService<global::ZeroAlloc.Outbox.IOutboxStore>(key),");
            sb.AppendLine("                    sp.GetRequiredService<global::ZeroAlloc.Outbox.IOutboxSerializer>()));");
            sb.AppendLine("            builder.Services.TryAddEnumerable(");
            sb.AppendLine($"                ServiceDescriptor.Transient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, {dispatcherName}>());");
            AppendDefaultDispatcher(sb, typeFqn, "            ");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        foreach (var (typeFqn, writerName, dispatcherName) in registrations)
        {
            sb.AppendLine($"            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxWriter<{typeFqn}>, {writerName}>();");
            sb.AppendLine($"            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, {dispatcherName}>();");
            AppendDefaultDispatcher(sb, typeFqn, "            ");
        }
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void AppendDefaultDispatcher(StringBuilder sb, string typeFqn, string indent)
    {
        sb.AppendLine($"{indent}builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<{typeFqn}>,");
        sb.AppendLine($"{indent}    global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<{typeFqn}>>();");
    }
}
