//HintName: PingMessage.Outbox.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Outbox;

internal sealed class PingMessageOutboxWriter : global::ZeroAlloc.Outbox.IOutboxWriter<global::PingMessage>
{
    private readonly global::ZeroAlloc.Outbox.IOutboxStore _store;
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;

    public PingMessageOutboxWriter(
        global::ZeroAlloc.Outbox.IOutboxStore store,
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer)
    {
        _store = store;
        _serializer = serializer;
    }

    public global::System.Threading.Tasks.ValueTask WriteAsync(
        global::PingMessage message,
        global::System.Data.Common.DbTransaction? transaction,
        global::System.Threading.CancellationToken ct)
        => _store.EnqueueAsync("PingMessage", _serializer.Serialize(message), transaction, ct);
}

internal sealed class PingMessageOutboxTypeDispatcher : global::ZeroAlloc.Outbox.IOutboxTypeDispatcher
{
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;
    private readonly global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage> _dispatcher;

    public PingMessageOutboxTypeDispatcher(
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer,
        global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage> dispatcher)
    {
        _serializer = serializer;
        _dispatcher = dispatcher;
    }

    public string TypeName => "PingMessage";

    public global::System.Threading.Tasks.ValueTask DispatchAsync(
        global::System.ReadOnlyMemory<byte> payload,
        global::System.Threading.CancellationToken ct)
    {
        var message = _serializer.Deserialize<global::PingMessage>(payload);
        return _dispatcher.DispatchAsync(message, ct);
    }
}

public static partial class OutboxServiceCollectionExtensions
{
    /// <summary>
    /// Registers the outbox writer and type dispatcher of this message type.
    /// </summary>
    /// <remarks>
    /// On a named pipeline's builder the writer is registered keyed by the pipeline's name, and
    /// writes to that pipeline's store: inject it with <c>[FromKeyedServices(name)]</c>. The type
    /// dispatcher is shared by every pipeline.
    /// </remarks>
    public static global::ZeroAlloc.Outbox.IOutboxBuilder AddPingMessageOutbox(
        this global::ZeroAlloc.Outbox.IOutboxBuilder builder)
    {
        if (builder is global::ZeroAlloc.Outbox.INamedOutboxBuilder named)
        {
            builder.Services.TryAddKeyedTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::PingMessage>>(
                named.Name,
                static (sp, key) => new PingMessageOutboxWriter(
                    sp.GetRequiredKeyedService<global::ZeroAlloc.Outbox.IOutboxStore>(key),
                    sp.GetRequiredService<global::ZeroAlloc.Outbox.IOutboxSerializer>()));
            builder.Services.TryAddEnumerable(
                ServiceDescriptor.Transient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, PingMessageOutboxTypeDispatcher>());
            builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage>,
                global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::PingMessage>>();
        }
        else
        {
            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::PingMessage>, PingMessageOutboxWriter>();
            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, PingMessageOutboxTypeDispatcher>();
            builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::PingMessage>,
                global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::PingMessage>>();
        }

        return builder;
    }
}
