//HintName: MyApp_OrderPlaced.Outbox.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace MyApp;

internal sealed class OrderPlacedOutboxWriter : global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.OrderPlaced>
{
    private readonly global::ZeroAlloc.Outbox.IOutboxStore _store;
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;

    public OrderPlacedOutboxWriter(
        global::ZeroAlloc.Outbox.IOutboxStore store,
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer)
    {
        _store = store;
        _serializer = serializer;
    }

    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "IOutboxSerializer is provided by the consumer; its trim-unsafety is their concern. The generated writer/dispatcher only forwards the call.")]
    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("AOT", "IL3050", Justification = "IOutboxSerializer is provided by the consumer; its AOT-unsafety is their concern. The generated writer/dispatcher only forwards the call.")]
    public global::System.Threading.Tasks.ValueTask WriteAsync(
        global::MyApp.OrderPlaced message,
        global::System.Data.Common.DbTransaction? transaction,
        global::System.Threading.CancellationToken ct)
        => _store.EnqueueAsync("MyApp.OrderPlaced", _serializer.Serialize(message), transaction, ct);
}

internal sealed class OrderPlacedOutboxTypeDispatcher : global::ZeroAlloc.Outbox.IOutboxTypeDispatcher
{
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;
    private readonly global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.OrderPlaced> _dispatcher;

    public OrderPlacedOutboxTypeDispatcher(
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer,
        global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.OrderPlaced> dispatcher)
    {
        _serializer = serializer;
        _dispatcher = dispatcher;
    }

    public string TypeName => "MyApp.OrderPlaced";

    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "IOutboxSerializer is provided by the consumer; its trim-unsafety is their concern. The generated writer/dispatcher only forwards the call.")]
    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("AOT", "IL3050", Justification = "IOutboxSerializer is provided by the consumer; its AOT-unsafety is their concern. The generated writer/dispatcher only forwards the call.")]
    public global::System.Threading.Tasks.ValueTask DispatchAsync(
        global::System.ReadOnlyMemory<byte> payload,
        global::System.Threading.CancellationToken ct)
    {
        var message = _serializer.Deserialize<global::MyApp.OrderPlaced>(payload);
        return _dispatcher.DispatchAsync(message, ct);
    }
}

public static partial class OutboxServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddOrderPlacedOutbox(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.AddTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.OrderPlaced>, OrderPlacedOutboxWriter>();
        services.AddTransient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, OrderPlacedOutboxTypeDispatcher>();
        services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.OrderPlaced>,
            global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::MyApp.OrderPlaced>>();
        return services;
    }
}
