//HintName: MyApp.StockReserved.Outbox.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Outbox;

namespace MyApp;

internal sealed class StockReservedOutboxWriter : global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.StockReserved>
{
    private readonly global::ZeroAlloc.Outbox.IOutboxStore _store;
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;

    public StockReservedOutboxWriter(
        global::ZeroAlloc.Outbox.IOutboxStore store,
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer)
    {
        _store = store;
        _serializer = serializer;
    }

    public global::System.Threading.Tasks.ValueTask WriteAsync(
        global::MyApp.StockReserved message,
        global::System.Data.Common.DbTransaction? transaction,
        global::System.Threading.CancellationToken ct)
        => _store.EnqueueAsync("MyApp.StockReserved", _serializer.Serialize(message), transaction, ct);
}

internal sealed class StockReservedOutboxTypeDispatcher : global::ZeroAlloc.Outbox.IOutboxTypeDispatcher
{
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;
    private readonly global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.StockReserved> _dispatcher;

    public StockReservedOutboxTypeDispatcher(
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer,
        global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.StockReserved> dispatcher)
    {
        _serializer = serializer;
        _dispatcher = dispatcher;
    }

    public string TypeName => "MyApp.StockReserved";

    public global::System.Threading.Tasks.ValueTask DispatchAsync(
        global::System.ReadOnlyMemory<byte> payload,
        global::System.Threading.CancellationToken ct)
    {
        var message = _serializer.Deserialize<global::MyApp.StockReserved>(payload);
        return _dispatcher.DispatchAsync(message, ct);
    }
}

public static partial class OutboxServiceCollectionExtensions
{
    /// <summary>
    /// Registers the outbox writer and type dispatcher of this message type.
    /// </summary>
    /// <remarks>
    /// On a named pipeline's builder the writer is registered keyed by the pipeline's name, and
    /// writes to that pipeline's store: inject it with <c>[FromKeyedServices(name)]</c>. The type
    /// dispatcher is shared by every pipeline.
    /// </remarks>
    public static global::ZeroAlloc.Outbox.IOutboxBuilder AddStockReservedOutbox(
        this global::ZeroAlloc.Outbox.IOutboxBuilder builder)
    {
        if (builder is global::ZeroAlloc.Outbox.INamedOutboxBuilder named)
        {
            builder.Services.TryAddKeyedTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.StockReserved>>(
                named.Name,
                static (sp, key) => new StockReservedOutboxWriter(
                    sp.GetRequiredKeyedService<global::ZeroAlloc.Outbox.IOutboxStore>(key),
                    sp.GetRequiredService<global::ZeroAlloc.Outbox.IOutboxSerializer>()));
            builder.Services.TryAddEnumerable(
                ServiceDescriptor.Transient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, StockReservedOutboxTypeDispatcher>());
            builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.StockReserved>,
                global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::MyApp.StockReserved>>();
        }
        else
        {
            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.StockReserved>, StockReservedOutboxWriter>();
            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, StockReservedOutboxTypeDispatcher>();
            builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.StockReserved>,
                global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::MyApp.StockReserved>>();
        }

        return builder;
    }
}
