//HintName: MyApp.Envelope`1.Outbox.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Outbox;

namespace MyApp;

internal sealed class EnvelopeOfOrderPlacedOutboxWriter : global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.Envelope<global::MyApp.OrderPlaced>>
{
    private readonly global::ZeroAlloc.Outbox.IOutboxStore _store;
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;

    public EnvelopeOfOrderPlacedOutboxWriter(
        global::ZeroAlloc.Outbox.IOutboxStore store,
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer)
    {
        _store = store;
        _serializer = serializer;
    }

    public global::System.Threading.Tasks.ValueTask WriteAsync(
        global::MyApp.Envelope<global::MyApp.OrderPlaced> message,
        global::System.Data.Common.DbTransaction? transaction,
        global::System.Threading.CancellationToken ct)
        => _store.EnqueueAsync("MyApp.Envelope<MyApp.OrderPlaced>", _serializer.Serialize(message), transaction, ct);
}

internal sealed class EnvelopeOfOrderPlacedOutboxTypeDispatcher : global::ZeroAlloc.Outbox.IOutboxTypeDispatcher
{
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;
    private readonly global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.Envelope<global::MyApp.OrderPlaced>> _dispatcher;

    public EnvelopeOfOrderPlacedOutboxTypeDispatcher(
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer,
        global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.Envelope<global::MyApp.OrderPlaced>> dispatcher)
    {
        _serializer = serializer;
        _dispatcher = dispatcher;
    }

    public string TypeName => "MyApp.Envelope<MyApp.OrderPlaced>";

    public global::System.Threading.Tasks.ValueTask DispatchAsync(
        global::System.ReadOnlyMemory<byte> payload,
        global::System.Threading.CancellationToken ct)
    {
        var message = _serializer.Deserialize<global::MyApp.Envelope<global::MyApp.OrderPlaced>>(payload);
        return _dispatcher.DispatchAsync(message, ct);
    }
}

internal sealed class EnvelopeOfStockReservedOutboxWriter : global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.Envelope<global::MyApp.StockReserved>>
{
    private readonly global::ZeroAlloc.Outbox.IOutboxStore _store;
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;

    public EnvelopeOfStockReservedOutboxWriter(
        global::ZeroAlloc.Outbox.IOutboxStore store,
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer)
    {
        _store = store;
        _serializer = serializer;
    }

    public global::System.Threading.Tasks.ValueTask WriteAsync(
        global::MyApp.Envelope<global::MyApp.StockReserved> message,
        global::System.Data.Common.DbTransaction? transaction,
        global::System.Threading.CancellationToken ct)
        => _store.EnqueueAsync("MyApp.Envelope<MyApp.StockReserved>", _serializer.Serialize(message), transaction, ct);
}

internal sealed class EnvelopeOfStockReservedOutboxTypeDispatcher : global::ZeroAlloc.Outbox.IOutboxTypeDispatcher
{
    private readonly global::ZeroAlloc.Outbox.IOutboxSerializer _serializer;
    private readonly global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.Envelope<global::MyApp.StockReserved>> _dispatcher;

    public EnvelopeOfStockReservedOutboxTypeDispatcher(
        global::ZeroAlloc.Outbox.IOutboxSerializer serializer,
        global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.Envelope<global::MyApp.StockReserved>> dispatcher)
    {
        _serializer = serializer;
        _dispatcher = dispatcher;
    }

    public string TypeName => "MyApp.Envelope<MyApp.StockReserved>";

    public global::System.Threading.Tasks.ValueTask DispatchAsync(
        global::System.ReadOnlyMemory<byte> payload,
        global::System.Threading.CancellationToken ct)
    {
        var message = _serializer.Deserialize<global::MyApp.Envelope<global::MyApp.StockReserved>>(payload);
        return _dispatcher.DispatchAsync(message, ct);
    }
}

public static partial class OutboxServiceCollectionExtensions
{
    /// <summary>
    /// Registers the outbox writer and type dispatcher of every closed construction of MyApp.Envelope&lt;T&gt;
    /// the generator found in this assembly.
    /// </summary>
    /// <remarks>
    /// On a named pipeline's builder the writer is registered keyed by the pipeline's name, and
    /// writes to that pipeline's store: inject it with <c>[FromKeyedServices(name)]</c>. The type
    /// dispatcher is shared by every pipeline.
    /// </remarks>
    public static global::ZeroAlloc.Outbox.IOutboxBuilder AddEnvelopeOutbox(
        this global::ZeroAlloc.Outbox.IOutboxBuilder builder)
    {
        if (builder is global::ZeroAlloc.Outbox.INamedOutboxBuilder named)
        {
            builder.Services.TryAddKeyedTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.Envelope<global::MyApp.OrderPlaced>>>(
                named.Name,
                static (sp, key) => new EnvelopeOfOrderPlacedOutboxWriter(
                    sp.GetRequiredKeyedService<global::ZeroAlloc.Outbox.IOutboxStore>(key),
                    sp.GetRequiredService<global::ZeroAlloc.Outbox.IOutboxSerializer>()));
            builder.Services.TryAddEnumerable(
                ServiceDescriptor.Transient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, EnvelopeOfOrderPlacedOutboxTypeDispatcher>());
            builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.Envelope<global::MyApp.OrderPlaced>>,
                global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::MyApp.Envelope<global::MyApp.OrderPlaced>>>();
            builder.Services.TryAddKeyedTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.Envelope<global::MyApp.StockReserved>>>(
                named.Name,
                static (sp, key) => new EnvelopeOfStockReservedOutboxWriter(
                    sp.GetRequiredKeyedService<global::ZeroAlloc.Outbox.IOutboxStore>(key),
                    sp.GetRequiredService<global::ZeroAlloc.Outbox.IOutboxSerializer>()));
            builder.Services.TryAddEnumerable(
                ServiceDescriptor.Transient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, EnvelopeOfStockReservedOutboxTypeDispatcher>());
            builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.Envelope<global::MyApp.StockReserved>>,
                global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::MyApp.Envelope<global::MyApp.StockReserved>>>();
        }
        else
        {
            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.Envelope<global::MyApp.OrderPlaced>>, EnvelopeOfOrderPlacedOutboxWriter>();
            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, EnvelopeOfOrderPlacedOutboxTypeDispatcher>();
            builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.Envelope<global::MyApp.OrderPlaced>>,
                global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::MyApp.Envelope<global::MyApp.OrderPlaced>>>();
            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxWriter<global::MyApp.Envelope<global::MyApp.StockReserved>>, EnvelopeOfStockReservedOutboxWriter>();
            builder.Services.AddTransient<global::ZeroAlloc.Outbox.IOutboxTypeDispatcher, EnvelopeOfStockReservedOutboxTypeDispatcher>();
            builder.Services.TryAddTransient<global::ZeroAlloc.Outbox.IOutboxDispatcher<global::MyApp.Envelope<global::MyApp.StockReserved>>,
                global::ZeroAlloc.Outbox.DefaultOutboxDispatcher<global::MyApp.Envelope<global::MyApp.StockReserved>>>();
        }

        return builder;
    }
}
