using ZeroAlloc.Serialisation;

namespace ZeroAlloc.Outbox;

/// <summary>
/// AOT-safe <see cref="IOutboxSerializer"/> implementation that delegates to an
/// <see cref="ISerializerDispatcher"/> generated by <c>ZeroAlloc.Serialisation</c>.
/// </summary>
/// <remarks>
/// Register by annotating your message types with <c>[ZeroAllocSerializable]</c> in the
/// consuming assembly and calling <c>services.AddSerializerDispatcher()</c> before
/// <c>AddOutbox()</c>. When an <see cref="ISerializerDispatcher"/> is present in the DI
/// container, <c>AddOutbox</c> automatically uses this class instead of the
/// reflection-based <see cref="SystemTextJsonOutboxSerializer"/>.
/// </remarks>
public sealed class DispatchingOutboxSerializer : IOutboxSerializer
{
    private readonly ISerializerDispatcher _dispatcher;

    public DispatchingOutboxSerializer(ISerializerDispatcher dispatcher)
        => _dispatcher = dispatcher ?? throw new ArgumentNullException(nameof(dispatcher));

    public ReadOnlyMemory<byte> Serialize<T>(T value) =>
        _dispatcher.Serialize(value!, typeof(T));

    public T Deserialize<T>(ReadOnlyMemory<byte> data)
    {
        var result = _dispatcher.Deserialize(data, typeof(T));
        return result is T typed
            ? typed
            : throw new InvalidOperationException(
                $"Deserializing {typeof(T).Name} returned null or wrong type.");
    }
}
